### ISSUE TITLE
Lightning RC4 not installed

### ISSUE THREAD

**Issue by davidgil** [acquia/lightning-project#10]
Hi,

i am trying to update a RC3 version but when i run "composer update", it install 8.1.0-beta5.

When i try to install a clean lightning using:

composer create-project acquia/lightning-project:^8.1.0 MY_PROJECT --no-interaction --stability rc

it also installs me: 

            "name": "drupal/lightning",
            "version": "8.1.0-beta5",

¿any ideas?

Best
David

**Comment by phenaproxima** [comment]
Ooh, good catch. I believe this is a problem in lightning-project.

Try this, though -- in your composer.json, try changing the drupal/lightning version constraint to ^8.1 and re-running composer update. If my suspicion is correct, that will bring it up to the latest RC.

**Comment by davidgil** [comment]
Changed lightning req to:

        "drupal/lightning": "^8.1",

but still downloading beta5

**Comment by balsama** [comment]
Possibly another dependency that requires an earlier version of drupal? Have you required any other dependencies in your project?

**Comment by davidgil** [comment]
It is happening with a clean lightning install, installed using: 

composer create-project acquia/lightning-project:^8.1.0 MY_PROJECT --no-interaction --stability rc

then i update: 
"drupal/lightning": "^8.1",

as suggested by @phenaproxima but the same occurs. attach composer.json & composer.lock



[composer.zip](https://github.com/acquia/lightning-project/files/257584/composer.zip)

**Comment by balsama** [comment]
Looks like we traced this down to a dependency conflict in drush. We were requiring drush dev because we rely on a patch that hasn't made it into a release. We are now requiring a specific version of drush and patching it to eliminate the possibility of it introducing conflicts like this in the future.

For now, you can require lightning dev in your lightning project (after running the standard `composer create-project` command):

    composer require drupal/lightning:dev-8.x-1.x

We'll make a new release tomorrow.

**Comment by phenaproxima** [comment]
Our RC5 release (which should fix this issue) is now out. You'll want to change the Lightning version constraint in composer.json to ^8.1@rc, then run composer update -- that SHOULD fix the problem!

**Comment by balsama** [comment]
Fixed in RC5
