### ISSUE TITLE
Warning: require(/var/www/html/../vendor/autoload.php): failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by magick93** [acquia/lightning-project#26]
Hello

I have run 

```
composer create-project acquia/lightning-project lightningdev
composer update
composer install
```
Running just the first command seems to be enough, in that there are no errors. The other two are just for good measure.

But when I try to run the generated drupal site I get:

```
Warning: require(/var/www/html/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/html/../vendor/autoload.php' (include_path='.:') in /var/www/html/autoload.php on line 17
```

Any ideas what I am doing wrong?

**Comment by balsama** [comment]
It looks like your webserver is serving pages from a different directory than where you built lightning. Lightning Project will build a docroot inside of the the `lightningdev` directory you created with the create-project directory.

So you should point your webserver to:

    /path/to/where/you/ran/create-project/lightningdev/docroot

**Comment by magick93** [comment]
Yes the webserver is point at the docroot directory.

**Comment by balsama** [comment]
> Yes the webserver is point at the docroot directory.

Your fatal error tells me otherwise. It shows that your webserver is pointed to the /var/www/html directory.

**Comment by magick93** [comment]
To clarify, Im running Drupal using docker-compose.

In the compose file I map the docroot to /var/www/html

    volumes:
      - ./lighning/docroot:/var/www/html

**Comment by brokenmachine** [comment]
It looks like some time has passed since discussion of this issue, but I am having the same problem (which I have solved, but in a non-optimal way).  On my first attempt, I built Lighting via Composer in my home directory, and then copied the contents of the generated _docroot_ directory to /var/www/html.  However, when running /core/install.php, I got the error and upon looking at what Composer generated, it became apparent that _autoload.php_ file was referencing the vendor directory **above** the _docroot_ directory, so I had to copy the entire directory that Composer generated, in order for that _vendor_ to be accessible.  Everything I read on Acquia says one should be able to make only the _docroot_ accessible to the web server.  Of course, this is not optimal, so perhaps the process I am following is not correct, let me know.

**Comment by balsama** [comment]
Hi @brokenmachine. The process you're following is correct. The _vendor_ directory in a composer-generated codebase is one level up from the docroot. And it is needed to run the application.

It's true that only docroot needs to be _served_ by the webserver, but the vendor and autoloader still need to be accessible to the application. It's possible that there is some outdated documentation from Acquia since this is a general shift in the Drupal community as a whole - away from packaged tarballs that contain dependencies.

**Comment by brokenmachine** [comment]
Thanks @balsama.  I'm on Apache (on Ubuntu) and the docroot was the default /var/www/html, so I ended up just placing the entire Composer-generated project under /var/www, and then reconfiguring Apache such that the docroot was /var/www/docroot, thereby making the Composer and Drupal happy and making my Drupal site accessible at the root from the browser.  So alls well that ends well.  I forgot that the _include_ directive in PHP is file-system based and the web document root doesn't matter for this, so all's well that ends well. :)

**Comment by nco71** [comment]
In the case of using docker , I don't think it is necessary to copy the files , the reason it cannot find the file is that those are not mounted , the best solution I found was to make my volume for the webserver and php to be organized that way : 

php / nginx / apache

volumes :
./www/ : /var/html

Then I set up the variable to inform the webserver root new location ( in web directory ) 

NGINX_SERVER_ROOT : /var/www/html/web/

**Comment by kamil-kielczewski** [comment]
Here is my case for laravel 5.5 nginx: https://stackoverflow.com/q/46950688/860099

**Comment by Gezgin7** [comment]
Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /home/kantmarble/domains/kantmarble.com/public_html/wp-content/themes/u-design/inc/admin/u-design-merlin/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/usr/local/lsws/lsphp5/lib/php') in /home/kantmarble/domains/kantmarble.com/public_html/wp-content/themes/u-design/inc/admin/u-design-merlin/vendor/autoload.php on line 5

Hi firends,
I am facing above problem at my wordpress site. Could any expert can say what i am doing wrong?
Thanks in advance,

**Comment by phenaproxima** [comment]
@Gezgin7, this repository is for a Drupal distribution, so it has nothing do with Wordpress and I don't think we'll be able to offer any useful advice on that. You may want to ask for support in whatever the Wordpress support channels are.

**Comment by bbbootstrap** [comment]
>
